### ISSUE TITLE
Didnt get Links working

### ISSUE THREAD

**Issue by arcronis** [allansun/docker-cloud-php-api#5]
Hello,
can anyone give me an code example how i can add Links ( from and to ) on Service creation ?

**Comment by yunmoxue** [comment]
`$FromService->addLinkedToService(Link::build(null, $ToService->getName(), 'the_alias_name_in_from_service');`

**Comment by arcronis** [comment]
thanks that should be working, but link from service does not work it dosnt add a Link from another service

**Comment by allansun** [comment]
Hi @arcronis, I think this is what you are looking for: https://github.com/allansun/docker-cloud-php-api/blob/master/src/API/Service.php#L223

pseudocode:
```php
$ServiceAPI = new \DockerCloud\API\Service();
$ServiceModel = $ServiceAPI->getByUri('xxxxxx');
$ServiceModel->addLinkedToService(Link::build(null, $ToService->getName(), 'the_alias_name_in_from_service');
$ServierModel = $ServiceAPI->updateLinkedToService($ServiceModel);
```
